app = "pi3-app"
primary_region = "iad"

[build]
dockerfile = "Dockerfile"

[env]
APP_ENV = "production"
APP_KEY = "base64:..."  # Garanta que está configurado
APP_DEBUG = "false"
DB_CONNECTION = "sqlite"
DB_DATABASE = "/database/database.sqlite"

[deploy]
release_command = "/bin/sh -c 'mkdir -p /database && touch /database/database.sqlite && php artisan migrate --force'"

[[mounts]]
source = "pi3_data"
destination = "/database"

[[services]]
internal_port = 8080
protocol = "tcp"

[[services.ports]]
handlers = ["http", "tls"]
port = 80
