# fly.toml file generated for pi3-app on Fly.io

app = "pi3-app"
primary_region = "iad" # Altere para a região mais próxima

[build]
dockerfile = "Dockerfile"

[env]
APP_ENV = "production"
APP_DEBUG = "false"
APP_URL = "https://pi3-app.fly.dev"
DB_CONNECTION = "sqlite"
DB_DATABASE = "/database/database.sqlite"
SESSION_DRIVER = "database"
QUEUE_CONNECTION = "database"

[[mounts]]
source = "pi3_data"
destination = "/database"

[deploy]
release_command = "mkdir -p /database && touch /database/database.sqlite && php artisan migrate --force"

[processes]
app = "php artisan serve --host=0.0.0.0 --port=8080"

[[services]]
internal_port = 8080
protocol = "tcp"
processes = ["app"]

[[services.ports]]
handlers = ["http", "tls"]
port = 80

[[services.ports]]
handlers = ["tls"]
port = 443

[[services.checks]]
type = "http"
interval = "10s"
timeout = "2s"
method = "get"
path = "/health"
